### ISSUE TITLE
Facebook Login Windows 8.1 and 10. Not authorized.

### ISSUE THREAD

**Issue by Firadzo** [MarkerMetro/MarkerMetro.Unity.WinIntegration#45]
Hi, thanks for this plugin. But unfortunately I having some issues with facebook login on PC build. I am building project with Unity 5.5.0 an also 5.5.3 for WSA 8.1. All was setup according to readme and all functionality seems to be working, facebook working on Windows Phone, but can't login on PC build, windows 8 and 10 tested. Also I tested on clear project only with raw plugin functionality. What am I missing?

Here is error message http://joxi.ru/KAgedYGugXPJQm
It's says "Not authorized. You are not logged in to system. Log in and try again" Translate may be not 100% accurate)

**Comment by hungweng** [comment]
Hi Firadzo, have you tried login to the test Facebook App? The app id is: 540541885996234

**Comment by Firadzo** [comment]
Hm, it is working, maybe I am don't setup correctly some settings on facebook console.

**Comment by Firadzo** [comment]
I set up facebook console according to this 
http://microsoft.github.io/winsdkfb/#

**Comment by hungweng** [comment]
Make sure "Embedded Browser OAuth Login" is enabled in your facebook app settings, it's located under Facebook Login -> Settings
![facebook](https://user-images.githubusercontent.com/7434251/29141232-6bd5adc2-7da1-11e7-8879-ed91be6f2722.PNG)

**Comment by Firadzo** [comment]
Yes it is was enabled :/
http://joxi.ru/v29aoOlUGpzNo2

**Comment by Firadzo** [comment]
Seems to me all correct, but I can't understand, maybe you can give me some permission to test app setup to compare?

**Comment by Firadzo** [comment]
I managed to solve the issue, disabling "web authorization OAuth" and removing link make facebook work on pc:/ (Currently tested on Windows 8.1 later will check Win10)
http://joxi.ru/YmEJGyDtZM5yY2
Thank you for help)
